version: '3'

services:

  my_webserver:
    build: my_webserver/
    tty: true
    # command: python manage.py runserver 0.0.0.0:8000
    # environment:
    #   - 'FLASK_RUN_HOST=0.0.0.0'
    volumes:
      - ./my_webserver:/my_webserver
    ports:
      - '8000:8000'