# Use an official Python runtime as a parent image
FROM python:3.8
ENV PYTHONUNBUFFERED 1

# Set the working directory to /my_webserver
WORKDIR /my_webserver

# Copy the current directory contents into the container
ADD . /my_webserver

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
# EXPOSE 5000

# CMD ["flask", "run"]